### ISSUE TITLE
[Bug] Unsupported method notification spam when switching to a buffer with LSP supported document highlight to another one which doesn't support it

### ISSUE THREAD

**Issue by pidgeon777** [ray-x/navigator.lua#191] opened 2022-05-27 13:02 UTC
```
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilato da runneradmin@fv-az320-113

Features: -acl +iconv +tui
See ":help feature-compile"

   file vimrc di sistema: "$VIM\sysinit.vim"
            $VIM di riserva: "C:/Program Files/nvim/share/nvim"
```

Scenario:

1. Open buffer A with LSP wich doesn't support `documentHighlightProvider`  capability
2. Open buffer B with LSP wich support `documentHighlightProvider`  capability
3. Switch back to buffer A

Now when moving cursors, in normal and insert mode, the vim.notify popup will appear in a spamming way for each cursor move stating that `method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer`.

OS: Windows 10 Pro

**Comment by ray-x** [comment] 2022-05-28 09:37
What language server are you using?
In the code, I specified that send highlight requests only when documentHighlightProvider is not nil.

**Comment by pidgeon777** [comment] 2022-05-28 12:44
LSP A is clangd/ccls, LSP B could be:

- marksman/zk -> Markdown buffer
- jsonls -> JSON buffer

all of which doesn't support the documentHighlight method.

So, it seems that when I start a LSP with documentHighlight method not supported, your plugin skip it, when I switch to a LSP that supports it then highlight get activated, but if I go back to the first buffer with unsupported method, something still tries to generate the documentHighlight requests, spamming the notification everytime I enter/leave/move cursor in insert or normal mode.

**Comment by pidgeon777** [comment] 2022-05-28 13:16
I just tried to switch from LSP A (no support documentHighlight), to LSP B - LUA (supports documentHighlight), and then back to LSP A, and the problem doesn't occur.

So, it seems that issue occurs when LSP B is clangd/ccls.

**Comment by ray-x** [comment] 2022-05-28 15:46
I can not reproduce with ccls and jsonls.
In fact, I have used nulls with other lsp for a long time. nulls does not support documentHighlight. Could you verify this issue with a minium config and latest version?

**Comment by ray-x** [comment] 2022-07-19 03:07
The notify spam occurs only happens when one lsp lying about the documentHighlight is supported but it doesn't.
If all the LSP does not support documentHighlight, the request wont sent.  And only when ALL lsp does not support documentHighlight but one lying it is supported, you will see that error.

Sometimes you may see this when a lsp server is slow in booting up. As cursorHold timer is normally 100~200ms, if the LSP failed to send a request back in that time frame, it will fail. But the behavior is not consistent. Once the LSP boot to ready and finish parser the project. It should work.

**Comment by ray-x** [comment] 2022-07-27 23:44
@pidgeon777 Are you still seeing this issue?

**Comment by avently** [comment] 2022-07-28 02:31
I have this issue too. 
I open a directory with `.ts` files, switching between files, then I open `.sh` file, notification with this error occurs. 
No notification shown when I open `.sh` file without opening `.ts` files first

**Comment by ray-x** [comment] 2022-07-28 03:18
Do you get spam messages or is it just once or twice?

If you get lots of spam messages, what Lsp server you are using. more specifically ,  What is the value of `server_capabilities.documentHighlightProvider` for those lsp ?

**Comment by ray-x** [comment] 2022-07-28 03:21
looks good to me. bashls supports documenthighlight
<img width="826" alt="image" src="https://user-images.githubusercontent.com/1681295/181413401-d9887bab-5ab8-479b-bb43-b27705bc8fad.png">

**Comment by avently** [comment] 2022-07-28 03:49
> Do you get spam messages or is it just once or twice?

Once after switch to `.sh` file. 

```log
 1 client(s) attached to this buffer: 
 Detected filetype:   sh

 Client: bashls (id: 4, pid: 1473056, bufnr: [10])
 	filetypes:       sh
 	autostart:       true
 	root directory:  /somerootdir
 	cmd:             /home/avently/.local/share/nvim/lsp_servers/bashls/node_modules/.bin/bash-language-server start
 
 1 active client(s) not attached to this buffer: 
 
 Client: tsserver (id: 2, pid: 1472926, bufnr: [9])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /somerootdir
 	cmd:             typescript-language-server --stdio
```

Take into account that I also use LunarVim which has it's own lspinstaller. Don't know if it is related or not, just in case.
Also you have null-ls while I use tsserver.

> What is the value of server_capabilities.documentHighlightProvider for those lsp ?

Have no idea how to find the answer on your question

**Comment by ray-x** [comment] 2022-07-28 04:04
In your case
only attached LSP is bashls
```
 1 client(s) attached to this buffer: 
 Detected filetype:   sh

 Client: bashls (id: 4, pid: 1473056, bufnr: [10])
```

tsserver is not attached to shell script buffer. (which is good)

Is the error message transient or persistent? 

There are cases that bashls reports `documentHightlightVendor = true` but it is not boot to ready to handle those requests. So you may see a few errors when it booting.

**Comment by avently** [comment] 2022-07-28 04:33
I don't use bashls often, so can't say. Just had this file opened in a tab and noticed that notification after switched to the file.

**Comment by ray-x** [comment] 2022-07-28 05:57
If you do see it constantly after the sh file is opened. that is an issue. Otherwise it more the lsp boot time is greater than your cursorhold delay setup.

**Comment by avently** [comment] 2022-07-28 11:40
Yeah, you are right. 
`set updatetime 3000`, tried the same steps and no issue. 
`set updatetime 300`, there is an issue again (this is my default value).

Out of curiuosity, removed `navigator`, reloaded nvim: no issues with even `set updatetime 30` while having working all LSP servers as is (thanks to LunarVim with it's setup). So this issue 100% can be avoided if other plugins don't produce this error, only `navigator` is.

**Comment by ray-x** [comment] 2022-07-28 18:35
1） I do not think LunarVim will load different Lsp based on your filetype after started neovim. Say you open ts file loading tsserver, then you load a bash file in same nvim instance, loading bashls, open markdown, load markdown-language-server.  
2) LSP documentHighlight is not enabled by lunarVim. So you wont see this issue.

**Comment by avently** [comment] 2022-07-28 19:42
>Say you open ts file loading tsserver, then you load a bash file in same nvim instance, loading bashls, open markdown, load markdown-language-server

This is literally what happens in my case. Autoloading without manual LspStart. On start all my previous session is restored (I use another plugin for this), then I just selecting open buffers one-by-one and everywhere I see started LSP server. Error checking works, same variable is highlighted in different places when I move cursor onto it.

> 2) LSP documentHighlight is not enabled by lunarVim. So you wont see this issue.

It's enabled:
https://github.com/LunarVim/LunarVim/blob/rolling/lua/lvim/lsp/config.lua#L77

How I can check it to make sure?

**Comment by ray-x** [comment] 2022-07-28 23:22
thanks, 
I pushed another PR, could you check if it works?

**Comment by avently** [comment] 2022-07-29 05:03
> could you check if it works?

It doesn't.

Video demonstration:

https://user-images.githubusercontent.com/7953703/181686205-5fcb4630-fff7-42c9-8964-b66e8bc14a6f.mp4

If you can't reproduce, maybe your system is so fast, try to make updatetime lower, like `set updatetime 1`, maybe it can help, don't know.

**Comment by ray-x** [comment] 2022-07-29 09:03
I did some cleanup. And also tried `updatime=1`
The bug should be fixed now.

**Comment by avently** [comment] 2022-07-29 18:19
Looks like you did! I'm unable to reproduce the problem with the same steps as before. Highlighting still works (with `document_highlight = true`, of course). 

Thank you for your professionalism.
Does your fix remove some functionality in order to make this happen or all functionality is the same?

**Comment by avently** [comment] 2022-07-29 18:38
I noticed one issue but I don't know the cause. It's not caused by the latest changes. 
Lua files managed by LunarVim (navigator config has `disable_lsp = { "rust_analyzer", "sumneko_lua" }`) because LunarVim injects Vim global named `lvim`. And it's painful to use init.lua without it. So when I open a file managed by `navigator` it highlights the words I select. Once I open Lua file highlighting works too but managed by LunarVim. Then I switch to non-lua file and highlighting stops working. Is it a confict you are aware of? Maybe is there a way to re-enable highlighting while cycling between lua <-> non-lua files? 
Video demonstration. Here highlighting stops working on `.ts` file but working on `.lua` and `.sh` (for some unknown reason):

https://user-images.githubusercontent.com/7953703/181822453-d797a73e-4b48-4dac-bf2d-641a921b3137.mp4

**Comment by ray-x** [comment] 2022-07-31 05:41
thanks for the video clips. I updated the code and it should solve the issue.

**Comment by avently** [comment] 2022-07-31 09:25
Fixed, thank you!

**Closed** 2022-07-31 09:26 UTC
